### ISSUE TITLE
Susu group creation

### ISSUE THREAD

**Issue by nickelbob** [sfncook/cryptosusu#1]
Requirements:

1. Deployment creates a new Susu group
2. The deployer of the contract is automatically set as the owner
3. The group is initialized with the following parameters - 
     - Name of the group [name]
     - Number of people in the group [number_recipients]
     - The frequency (monthly?  weekly?) [frequency]
     - The contribution rates (1 ETH, 0.1 ETH) [contribution_amt]
4. Group should be ready for others to join

**Comment by sfncook** [comment]
@nickelbob You also will need to create an API endpoint on the backend so the frontend can make the request.  Likewise the frontend will need to add some sort of "deploy" or "create" button for users to click

**Comment by bryantjk** [comment]
I'm taking a stab at this.

**Comment by nickelbob** [comment]
@sfncook can you say more about creating an endpoint? I thought public functions in the contract were automatically call-able?

**Comment by sfncook** [comment]
Actually, I've kind of changed my tune on this one, @nickelbob.  I think the right way to do this is from the frontend.  I'll tinker with it today and see if I can get it to work.  Check out issue #17
