### ISSUE TITLE
Should we add an "eviction" action - so the group owner can kick someone out of the group?

### ISSUE THREAD

**Issue by sfncook** [sfncook/cryptosusu#13]

**Comment by bryantjk** [comment]
Perhaps, but I don't think this should be an MVP feature, unless someone can make an argument for it being functionality likely to important to the next project.

**Comment by bryantjk** [comment]
Thinking about this a bit more...multi-signature transaction is a piece of functionality that I think would be useful as I think its a pretty foundational technique we'll need to master for future project. So perhaps we make it so that a majority of the members of a Susu sign-off on the eviction.

**Comment by sfncook** [comment]
I agree this is not really something for MVP
