### ISSUE TITLE
Should we log all transactions using a fallback function?

### ISSUE THREAD

**Issue by sfncook** [sfncook/cryptosusu#15]

**Comment by bryantjk** [comment]
So I didn't know about the fallback function (http://solidity.readthedocs.io/en/latest/contracts.html#fallback-function) until reading the question. Looks like it will be required for our usage, but not sure what @sfncook means by logging all transactions with it.

**Comment by nickelbob** [comment]
So I implemented a fallback func that just calls our contribute() method. I'm also not sure what @sfncook means by logging it - seems like you can fire off events and use those to log things but I haven't dug too deep into that.

**Comment by sfncook** [comment]
Yeah, I didn't research this or anything, but I read in a few places that just mentioned "logging transactions from the fallback function".  I guess I was thinking along the lines of visibility and traceability, which are two very important features for systems, like this, where we don't have much control over something once it's deployed.  If something goes wrong or whatever we might want some logging telling us what happened and when.  Really not a big deal.  We can put this in the ice box or just close it.
