### ISSUE TITLE
Should we apply a limit to the group amount?

### ISSUE THREAD

**Issue by sfncook** [sfncook/cryptosusu#16]
https://consensys.github.io/smart-contract-best-practices/software_engineering/#restrict-amount-of-ether-per-usercontract

**Comment by bryantjk** [comment]
Yes, @nickelbob and I talked about this briefly we need to limit the eth as well as the number of members a group can have. 10 for max group size?

**Comment by nickelbob** [comment]
I put 100 just cause I didn't see this. :)
