### ISSUE TITLE
Enable User Contribution to Susu

### ISSUE THREAD

**Issue by bryantjk** [sfncook/cryptosusu#4]
Once the group is full (the number of those who have Joined from #2 matches “number_recipients”) then it is ready for contributions.  Each recipient visits the website and clicks the “contribute” button to chip in their share. The contribution amount MUST match the contribution_amt or it will be rejected and the contribution will not count. The page reflects who has and has-not contributed for this cycle and how much each person contributed.  The contract records how much each recipient has contributed.

**Comment by nickelbob** [comment]
Backend done
