### ISSUE TITLE
Enable Susu Payouts

### ISSUE THREAD

**Issue by bryantjk** [sfncook/cryptosusu#5]
The group owner is then responsible for clicking the “Pay Out” button at the end of the cycle. The owner cannot invoke this action if the group is not full of people and all people have posted their contributions for this cycle.

**Comment by bryantjk** [comment]
Per Shawn: 
"I think the owner should be blocked from paying out until the cycle has expired. This will require also keeping track (in the contract variables) of one or more of the following:
- The last time the payout occurred (date/time stamp)
- A fixed or calculable date(s) for the cycle periods
- A list of all the past payout date/time stamps"

**Comment by sfncook** [comment]
Closing this for now.  If we want to enhance payout behavior we can open a more specific issue for the enhancement
